//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPMEnexo
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pedido.webservice.opmenexo.com/", ConfigurationName="OPMEnexo.IWSPedido")]
    public interface IWSPedido
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="alterarPedido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<OPMEnexo.wsRespostaIncluirPedido> alterarPedidoAsync(OPMEnexo.Usuario Usuario, OPMEnexo.pedido Pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="atualizarCadastroProduto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<OPMEnexo.wsResposta> atualizarCadastroProdutoAsync(OPMEnexo.Usuario Usuario, OPMEnexo.pedido Pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="autorizarFaturamento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<OPMEnexo.wsResposta> autorizarFaturamentoAsync(OPMEnexo.Usuario Usuario, OPMEnexo.pedido Pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="autorizarPedido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<OPMEnexo.wsResposta> autorizarPedidoAsync(OPMEnexo.Usuario Usuario, int Id_Pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="autorizarPedidoProduto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<OPMEnexo.wsResposta> autorizarPedidoProdutoAsync(OPMEnexo.Usuario Usuario, OPMEnexo.pedido Pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="cancelarPedido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<OPMEnexo.wsResposta> cancelarPedidoAsync(OPMEnexo.Usuario Usuario, OPMEnexo.pedido Pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="confirmarPedido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<OPMEnexo.wsResposta> confirmarPedidoAsync(OPMEnexo.Usuario Usuario, OPMEnexo.pedido Pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="consultarProdutos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<OPMEnexo.wsProduto> consultarProdutosAsync(OPMEnexo.Usuario Usuario, OPMEnexo.consultaProdutos Consulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="consultarStatusPedido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<OPMEnexo.wsResposta> consultarStatusPedidoAsync(OPMEnexo.Usuario Usuario, int Id_Pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="incluirItensCarrinho", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<OPMEnexo.wsResposta> incluirItensCarrinhoAsync(OPMEnexo.Usuario Usuario, OPMEnexo.pedido Pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="incluirItensExtras", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<OPMEnexo.wsResposta> incluirItensExtrasAsync(OPMEnexo.Usuario Usuario, OPMEnexo.pedido Pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="incluirPedido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<OPMEnexo.wsRespostaIncluirPedido> incluirPedidoAsync(OPMEnexo.Usuario Usuario, OPMEnexo.pedido Pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="incluirPedidoReposicao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<OPMEnexo.wsRespostaIncluirPedido> incluirPedidoReposicaoAsync(OPMEnexo.Usuario Usuario, OPMEnexo.pedido Pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="listarCadastroProduto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<OPMEnexo.wsProduto> listarCadastroProdutoAsync(OPMEnexo.Usuario Usuario, int Id_Pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="listarCarrinho", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<OPMEnexo.wsRespostaListarPedido> listarCarrinhoAsync(OPMEnexo.Usuario Usuario, int Id_Pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="resgatarFornecedor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<OPMEnexo.wsRespostaListarPedido> listarResgateFornecedorAsync(OPMEnexo.Usuario Usuario, int Id_Pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="listarRespostasPedido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<OPMEnexo.wsRespostaListarPedido> listarRespostasPedidoAsync(OPMEnexo.Usuario Usuario, int Id_Pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="listarRespostasPedidoConfirmado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<OPMEnexo.wsRespostaListarPedido> listarRespostasPedidoConfirmadoAsync(OPMEnexo.Usuario Usuario, int Id_Pedido);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="webservice")]
    public partial class Usuario
    {
        
        private string loginField;
        
        private string senhaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string login
        {
            get
            {
                return this.loginField;
            }
            set
            {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string senha
        {
            get
            {
                return this.senhaField;
            }
            set
            {
                this.senhaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.webservice.opmenexo.com/")]
    public partial class consultaProdutos
    {
        
        private produto[] produtosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Produto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public produto[] Produtos
        {
            get
            {
                return this.produtosField;
            }
            set
            {
                this.produtosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.webservice.opmenexo.com/")]
    public partial class produto
    {
        
        private int id_ProdutoField;
        
        private bool id_ProdutoFieldSpecified;
        
        private string descricao_Produto_MarcaField;
        
        private string descricao_ProdutoField;
        
        private int id_MarcaField;
        
        private bool id_MarcaFieldSpecified;
        
        private string nome_MarcaField;
        
        private string referenciaField;
        
        private string numero_RmsField;
        
        private string data_ValidadeField;
        
        private string unidade_MedidaField;
        
        private string codigo_ProdutoField;
        
        private string preco_ReferenciaField;
        
        private string preco_InicialField;
        
        private campoExtra[] campos_ExtraField;
        
        private string tussField;
        
        private string descricao_detalhadaField;
        
        private string descricao_resumida_materialField;
        
        private string especialidadeField;
        
        private string ncmField;
        
        private string fabricanteField;
        
        private string endereco_fabricanteField;
        
        private decimal valor_contratadoField;
        
        private bool valor_contratadoFieldSpecified;
        
        private string pais_origemField;
        
        private string materia_primaField;
        
        private string descricao_tecnicaField;
        
        private string classificacao_produtoField;
        
        private string origem_negociacao_contratoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Id_Produto
        {
            get
            {
                return this.id_ProdutoField;
            }
            set
            {
                this.id_ProdutoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Id_ProdutoSpecified
        {
            get
            {
                return this.id_ProdutoFieldSpecified;
            }
            set
            {
                this.id_ProdutoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Descricao_Produto_Marca
        {
            get
            {
                return this.descricao_Produto_MarcaField;
            }
            set
            {
                this.descricao_Produto_MarcaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Descricao_Produto
        {
            get
            {
                return this.descricao_ProdutoField;
            }
            set
            {
                this.descricao_ProdutoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int Id_Marca
        {
            get
            {
                return this.id_MarcaField;
            }
            set
            {
                this.id_MarcaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Id_MarcaSpecified
        {
            get
            {
                return this.id_MarcaFieldSpecified;
            }
            set
            {
                this.id_MarcaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Nome_Marca
        {
            get
            {
                return this.nome_MarcaField;
            }
            set
            {
                this.nome_MarcaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Referencia
        {
            get
            {
                return this.referenciaField;
            }
            set
            {
                this.referenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Numero_Rms
        {
            get
            {
                return this.numero_RmsField;
            }
            set
            {
                this.numero_RmsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Data_Validade
        {
            get
            {
                return this.data_ValidadeField;
            }
            set
            {
                this.data_ValidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Unidade_Medida
        {
            get
            {
                return this.unidade_MedidaField;
            }
            set
            {
                this.unidade_MedidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Codigo_Produto
        {
            get
            {
                return this.codigo_ProdutoField;
            }
            set
            {
                this.codigo_ProdutoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Preco_Referencia
        {
            get
            {
                return this.preco_ReferenciaField;
            }
            set
            {
                this.preco_ReferenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Preco_Inicial
        {
            get
            {
                return this.preco_InicialField;
            }
            set
            {
                this.preco_InicialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Campo_Extra", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public campoExtra[] Campos_Extra
        {
            get
            {
                return this.campos_ExtraField;
            }
            set
            {
                this.campos_ExtraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string tuss
        {
            get
            {
                return this.tussField;
            }
            set
            {
                this.tussField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string descricao_detalhada
        {
            get
            {
                return this.descricao_detalhadaField;
            }
            set
            {
                this.descricao_detalhadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string descricao_resumida_material
        {
            get
            {
                return this.descricao_resumida_materialField;
            }
            set
            {
                this.descricao_resumida_materialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string especialidade
        {
            get
            {
                return this.especialidadeField;
            }
            set
            {
                this.especialidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string ncm
        {
            get
            {
                return this.ncmField;
            }
            set
            {
                this.ncmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string fabricante
        {
            get
            {
                return this.fabricanteField;
            }
            set
            {
                this.fabricanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string endereco_fabricante
        {
            get
            {
                return this.endereco_fabricanteField;
            }
            set
            {
                this.endereco_fabricanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public decimal valor_contratado
        {
            get
            {
                return this.valor_contratadoField;
            }
            set
            {
                this.valor_contratadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valor_contratadoSpecified
        {
            get
            {
                return this.valor_contratadoFieldSpecified;
            }
            set
            {
                this.valor_contratadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string pais_origem
        {
            get
            {
                return this.pais_origemField;
            }
            set
            {
                this.pais_origemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string materia_prima
        {
            get
            {
                return this.materia_primaField;
            }
            set
            {
                this.materia_primaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string descricao_tecnica
        {
            get
            {
                return this.descricao_tecnicaField;
            }
            set
            {
                this.descricao_tecnicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string classificacao_produto
        {
            get
            {
                return this.classificacao_produtoField;
            }
            set
            {
                this.classificacao_produtoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string origem_negociacao_contrato
        {
            get
            {
                return this.origem_negociacao_contratoField;
            }
            set
            {
                this.origem_negociacao_contratoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.webservice.opmenexo.com/")]
    public partial class campoExtra
    {
        
        private string nomeField;
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Nome
        {
            get
            {
                return this.nomeField;
            }
            set
            {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(wsRespostaIncluirPedido))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(wsRespostaListarPedido))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(wsProduto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.webservice.opmenexo.com/")]
    public partial class wsResposta
    {
        
        private string[] mensagemField;
        
        private System.DateTime dataExecucaoField;
        
        private bool dataExecucaoFieldSpecified;
        
        private string infoField;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensagem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string[] mensagem
        {
            get
            {
                return this.mensagemField;
            }
            set
            {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime dataExecucao
        {
            get
            {
                return this.dataExecucaoField;
            }
            set
            {
                this.dataExecucaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataExecucaoSpecified
        {
            get
            {
                return this.dataExecucaoFieldSpecified;
            }
            set
            {
                this.dataExecucaoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string info
        {
            get
            {
                return this.infoField;
            }
            set
            {
                this.infoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.webservice.opmenexo.com/")]
    public partial class wsRespostaIncluirPedido : wsResposta
    {
        
        private int idPedidoField;
        
        private string[] mensagensField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idPedido
        {
            get
            {
                return this.idPedidoField;
            }
            set
            {
                this.idPedidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensagens", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string[] mensagens
        {
            get
            {
                return this.mensagensField;
            }
            set
            {
                this.mensagensField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.webservice.opmenexo.com/")]
    public partial class wsRespostaListarPedido : wsResposta
    {
        
        private pedido pedidoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public pedido pedido
        {
            get
            {
                return this.pedidoField;
            }
            set
            {
                this.pedidoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.webservice.opmenexo.com/")]
    public partial class pedido
    {
        
        private int id_PedidoField;
        
        private bool id_PedidoFieldSpecified;
        
        private cabecalhoPedido cabecalhoField;
        
        private procedimento[] procedimentos_AdicionaisField;
        
        private fornecedor[] fornecedoresField;
        
        private itemPedido[] itensField;
        
        private string codTipoPedidoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Id_Pedido
        {
            get
            {
                return this.id_PedidoField;
            }
            set
            {
                this.id_PedidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Id_PedidoSpecified
        {
            get
            {
                return this.id_PedidoFieldSpecified;
            }
            set
            {
                this.id_PedidoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cabecalhoPedido Cabecalho
        {
            get
            {
                return this.cabecalhoField;
            }
            set
            {
                this.cabecalhoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Procedimento_Adicional", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public procedimento[] Procedimentos_Adicionais
        {
            get
            {
                return this.procedimentos_AdicionaisField;
            }
            set
            {
                this.procedimentos_AdicionaisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Fornecedor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public fornecedor[] Fornecedores
        {
            get
            {
                return this.fornecedoresField;
            }
            set
            {
                this.fornecedoresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public itemPedido[] Itens
        {
            get
            {
                return this.itensField;
            }
            set
            {
                this.itensField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string codTipoPedido
        {
            get
            {
                return this.codTipoPedidoField;
            }
            set
            {
                this.codTipoPedidoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.webservice.opmenexo.com/")]
    public partial class cabecalhoPedido
    {
        
        private string titulo_PdcField;
        
        private string contatoField;
        
        private string id_Forma_PagamentoField;
        
        private string data_VencimentoField;
        
        private string hora_VencimentoField;
        
        private string moedaField;
        
        private string observacaoField;
        
        private string termos_CondicoesField;
        
        private string cod_ProcedimentoField;
        
        private string data_ProcedimentoField;
        
        private string hora_ProcedimentoField;
        
        private string pacienteField;
        
        private string matriculaField;
        
        private string medicoField;
        
        private string cRMField;
        
        private string cRM_UFField;
        
        private string convenioField;
        
        private string cNPJ_ConvenioField;
        
        private string cod_Endereco_EntregaField;
        
        private string cod_AgendamentoField;
        
        private string requisicaoField;
        
        private campoExtra[] camposExtraField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Titulo_Pdc
        {
            get
            {
                return this.titulo_PdcField;
            }
            set
            {
                this.titulo_PdcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Contato
        {
            get
            {
                return this.contatoField;
            }
            set
            {
                this.contatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Id_Forma_Pagamento
        {
            get
            {
                return this.id_Forma_PagamentoField;
            }
            set
            {
                this.id_Forma_PagamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Data_Vencimento
        {
            get
            {
                return this.data_VencimentoField;
            }
            set
            {
                this.data_VencimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Hora_Vencimento
        {
            get
            {
                return this.hora_VencimentoField;
            }
            set
            {
                this.hora_VencimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Moeda
        {
            get
            {
                return this.moedaField;
            }
            set
            {
                this.moedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Observacao
        {
            get
            {
                return this.observacaoField;
            }
            set
            {
                this.observacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Termos_Condicoes
        {
            get
            {
                return this.termos_CondicoesField;
            }
            set
            {
                this.termos_CondicoesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Cod_Procedimento
        {
            get
            {
                return this.cod_ProcedimentoField;
            }
            set
            {
                this.cod_ProcedimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Data_Procedimento
        {
            get
            {
                return this.data_ProcedimentoField;
            }
            set
            {
                this.data_ProcedimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Hora_Procedimento
        {
            get
            {
                return this.hora_ProcedimentoField;
            }
            set
            {
                this.hora_ProcedimentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Paciente
        {
            get
            {
                return this.pacienteField;
            }
            set
            {
                this.pacienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Matricula
        {
            get
            {
                return this.matriculaField;
            }
            set
            {
                this.matriculaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Medico
        {
            get
            {
                return this.medicoField;
            }
            set
            {
                this.medicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string CRM
        {
            get
            {
                return this.cRMField;
            }
            set
            {
                this.cRMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string CRM_UF
        {
            get
            {
                return this.cRM_UFField;
            }
            set
            {
                this.cRM_UFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string Convenio
        {
            get
            {
                return this.convenioField;
            }
            set
            {
                this.convenioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string CNPJ_Convenio
        {
            get
            {
                return this.cNPJ_ConvenioField;
            }
            set
            {
                this.cNPJ_ConvenioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string Cod_Endereco_Entrega
        {
            get
            {
                return this.cod_Endereco_EntregaField;
            }
            set
            {
                this.cod_Endereco_EntregaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string Cod_Agendamento
        {
            get
            {
                return this.cod_AgendamentoField;
            }
            set
            {
                this.cod_AgendamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string Requisicao
        {
            get
            {
                return this.requisicaoField;
            }
            set
            {
                this.requisicaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Campo_Extra", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public campoExtra[] camposExtra
        {
            get
            {
                return this.camposExtraField;
            }
            set
            {
                this.camposExtraField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.webservice.opmenexo.com/")]
    public partial class procedimento
    {
        
        private string cod_ProcedimentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Cod_Procedimento
        {
            get
            {
                return this.cod_ProcedimentoField;
            }
            set
            {
                this.cod_ProcedimentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.webservice.opmenexo.com/")]
    public partial class fornecedor
    {
        
        private string nome_FantasiaField;
        
        private string razao_SocialField;
        
        private string cNPJField;
        
        private string cod_FornecedorField;
        
        private string faturamento_MinimoField;
        
        private string prazo_EntregaField;
        
        private string validade_PropostaField;
        
        private int id_Forma_PagamentoField;
        
        private bool id_Forma_PagamentoFieldSpecified;
        
        private string freteField;
        
        private string resgatadoField;
        
        private campoExtra[] campos_ExtraField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Nome_Fantasia
        {
            get
            {
                return this.nome_FantasiaField;
            }
            set
            {
                this.nome_FantasiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Razao_Social
        {
            get
            {
                return this.razao_SocialField;
            }
            set
            {
                this.razao_SocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CNPJ
        {
            get
            {
                return this.cNPJField;
            }
            set
            {
                this.cNPJField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Cod_Fornecedor
        {
            get
            {
                return this.cod_FornecedorField;
            }
            set
            {
                this.cod_FornecedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Faturamento_Minimo
        {
            get
            {
                return this.faturamento_MinimoField;
            }
            set
            {
                this.faturamento_MinimoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Prazo_Entrega
        {
            get
            {
                return this.prazo_EntregaField;
            }
            set
            {
                this.prazo_EntregaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Validade_Proposta
        {
            get
            {
                return this.validade_PropostaField;
            }
            set
            {
                this.validade_PropostaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int Id_Forma_Pagamento
        {
            get
            {
                return this.id_Forma_PagamentoField;
            }
            set
            {
                this.id_Forma_PagamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Id_Forma_PagamentoSpecified
        {
            get
            {
                return this.id_Forma_PagamentoFieldSpecified;
            }
            set
            {
                this.id_Forma_PagamentoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Frete
        {
            get
            {
                return this.freteField;
            }
            set
            {
                this.freteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Resgatado
        {
            get
            {
                return this.resgatadoField;
            }
            set
            {
                this.resgatadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Campo_Extra", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public campoExtra[] Campos_Extra
        {
            get
            {
                return this.campos_ExtraField;
            }
            set
            {
                this.campos_ExtraField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.webservice.opmenexo.com/")]
    public partial class itemPedido
    {
        
        private int id_ArtigoField;
        
        private bool id_ArtigoFieldSpecified;
        
        private int id_MarcaField;
        
        private bool id_MarcaFieldSpecified;
        
        private string desc_MarcaField;
        
        private string codigo_ProdutoField;
        
        private string quantidadeField;
        
        private string[] loteField;
        
        private string nota_FiscalField;
        
        private string cnpj_FornecedorField;
        
        private campoExtra[] campos_ExtraField;
        
        private string tUSSField;
        
        private int id_ContratoField;
        
        private bool id_ContratoFieldSpecified;
        
        private respostaPedido[] respostasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int Id_Artigo
        {
            get
            {
                return this.id_ArtigoField;
            }
            set
            {
                this.id_ArtigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Id_ArtigoSpecified
        {
            get
            {
                return this.id_ArtigoFieldSpecified;
            }
            set
            {
                this.id_ArtigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int Id_Marca
        {
            get
            {
                return this.id_MarcaField;
            }
            set
            {
                this.id_MarcaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Id_MarcaSpecified
        {
            get
            {
                return this.id_MarcaFieldSpecified;
            }
            set
            {
                this.id_MarcaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Desc_Marca
        {
            get
            {
                return this.desc_MarcaField;
            }
            set
            {
                this.desc_MarcaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Codigo_Produto
        {
            get
            {
                return this.codigo_ProdutoField;
            }
            set
            {
                this.codigo_ProdutoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Quantidade
        {
            get
            {
                return this.quantidadeField;
            }
            set
            {
                this.quantidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Lote", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string[] Lote
        {
            get
            {
                return this.loteField;
            }
            set
            {
                this.loteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Nota_Fiscal
        {
            get
            {
                return this.nota_FiscalField;
            }
            set
            {
                this.nota_FiscalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Cnpj_Fornecedor
        {
            get
            {
                return this.cnpj_FornecedorField;
            }
            set
            {
                this.cnpj_FornecedorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Campo_Extra", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public campoExtra[] Campos_Extra
        {
            get
            {
                return this.campos_ExtraField;
            }
            set
            {
                this.campos_ExtraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string TUSS
        {
            get
            {
                return this.tUSSField;
            }
            set
            {
                this.tUSSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int Id_Contrato
        {
            get
            {
                return this.id_ContratoField;
            }
            set
            {
                this.id_ContratoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Id_ContratoSpecified
        {
            get
            {
                return this.id_ContratoFieldSpecified;
            }
            set
            {
                this.id_ContratoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Resposta", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public respostaPedido[] Respostas
        {
            get
            {
                return this.respostasField;
            }
            set
            {
                this.respostasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.webservice.opmenexo.com/")]
    public partial class respostaPedido
    {
        
        private string cNPJField;
        
        private string fabricanteField;
        
        private string embalagemField;
        
        private string preco_UnitarioField;
        
        private string preco_TotalField;
        
        private string comentarioField;
        
        private campoExtra[] campos_ExtraField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CNPJ
        {
            get
            {
                return this.cNPJField;
            }
            set
            {
                this.cNPJField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Fabricante
        {
            get
            {
                return this.fabricanteField;
            }
            set
            {
                this.fabricanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Embalagem
        {
            get
            {
                return this.embalagemField;
            }
            set
            {
                this.embalagemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Preco_Unitario
        {
            get
            {
                return this.preco_UnitarioField;
            }
            set
            {
                this.preco_UnitarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Preco_Total
        {
            get
            {
                return this.preco_TotalField;
            }
            set
            {
                this.preco_TotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Comentario
        {
            get
            {
                return this.comentarioField;
            }
            set
            {
                this.comentarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Campo_Extra", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public campoExtra[] Campos_Extra
        {
            get
            {
                return this.campos_ExtraField;
            }
            set
            {
                this.campos_ExtraField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pedido.webservice.opmenexo.com/")]
    public partial class wsProduto : wsResposta
    {
        
        private produto[] produtosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Produtos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public produto[] Produtos
        {
            get
            {
                return this.produtosField;
            }
            set
            {
                this.produtosField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IWSPedidoChannel : OPMEnexo.IWSPedido, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class WSPedidoClient : System.ServiceModel.ClientBase<OPMEnexo.IWSPedido>, OPMEnexo.IWSPedido
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSPedidoClient() : 
                base(WSPedidoClient.GetDefaultBinding(), WSPedidoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSPedidoPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSPedidoClient(EndpointConfiguration endpointConfiguration) : 
                base(WSPedidoClient.GetBindingForEndpoint(endpointConfiguration), WSPedidoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSPedidoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSPedidoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSPedidoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSPedidoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSPedidoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<OPMEnexo.wsRespostaIncluirPedido> alterarPedidoAsync(OPMEnexo.Usuario Usuario, OPMEnexo.pedido Pedido)
        {
            return base.Channel.alterarPedidoAsync(Usuario, Pedido);
        }
        
        public System.Threading.Tasks.Task<OPMEnexo.wsResposta> atualizarCadastroProdutoAsync(OPMEnexo.Usuario Usuario, OPMEnexo.pedido Pedido)
        {
            return base.Channel.atualizarCadastroProdutoAsync(Usuario, Pedido);
        }
        
        public System.Threading.Tasks.Task<OPMEnexo.wsResposta> autorizarFaturamentoAsync(OPMEnexo.Usuario Usuario, OPMEnexo.pedido Pedido)
        {
            return base.Channel.autorizarFaturamentoAsync(Usuario, Pedido);
        }
        
        public System.Threading.Tasks.Task<OPMEnexo.wsResposta> autorizarPedidoAsync(OPMEnexo.Usuario Usuario, int Id_Pedido)
        {
            return base.Channel.autorizarPedidoAsync(Usuario, Id_Pedido);
        }
        
        public System.Threading.Tasks.Task<OPMEnexo.wsResposta> autorizarPedidoProdutoAsync(OPMEnexo.Usuario Usuario, OPMEnexo.pedido Pedido)
        {
            return base.Channel.autorizarPedidoProdutoAsync(Usuario, Pedido);
        }
        
        public System.Threading.Tasks.Task<OPMEnexo.wsResposta> cancelarPedidoAsync(OPMEnexo.Usuario Usuario, OPMEnexo.pedido Pedido)
        {
            return base.Channel.cancelarPedidoAsync(Usuario, Pedido);
        }
        
        public System.Threading.Tasks.Task<OPMEnexo.wsResposta> confirmarPedidoAsync(OPMEnexo.Usuario Usuario, OPMEnexo.pedido Pedido)
        {
            return base.Channel.confirmarPedidoAsync(Usuario, Pedido);
        }
        
        public System.Threading.Tasks.Task<OPMEnexo.wsProduto> consultarProdutosAsync(OPMEnexo.Usuario Usuario, OPMEnexo.consultaProdutos Consulta)
        {
            return base.Channel.consultarProdutosAsync(Usuario, Consulta);
        }
        
        public System.Threading.Tasks.Task<OPMEnexo.wsResposta> consultarStatusPedidoAsync(OPMEnexo.Usuario Usuario, int Id_Pedido)
        {
            return base.Channel.consultarStatusPedidoAsync(Usuario, Id_Pedido);
        }
        
        public System.Threading.Tasks.Task<OPMEnexo.wsResposta> incluirItensCarrinhoAsync(OPMEnexo.Usuario Usuario, OPMEnexo.pedido Pedido)
        {
            return base.Channel.incluirItensCarrinhoAsync(Usuario, Pedido);
        }
        
        public System.Threading.Tasks.Task<OPMEnexo.wsResposta> incluirItensExtrasAsync(OPMEnexo.Usuario Usuario, OPMEnexo.pedido Pedido)
        {
            return base.Channel.incluirItensExtrasAsync(Usuario, Pedido);
        }
        
        public System.Threading.Tasks.Task<OPMEnexo.wsRespostaIncluirPedido> incluirPedidoAsync(OPMEnexo.Usuario Usuario, OPMEnexo.pedido Pedido)
        {
            return base.Channel.incluirPedidoAsync(Usuario, Pedido);
        }
        
        public System.Threading.Tasks.Task<OPMEnexo.wsRespostaIncluirPedido> incluirPedidoReposicaoAsync(OPMEnexo.Usuario Usuario, OPMEnexo.pedido Pedido)
        {
            return base.Channel.incluirPedidoReposicaoAsync(Usuario, Pedido);
        }
        
        public System.Threading.Tasks.Task<OPMEnexo.wsProduto> listarCadastroProdutoAsync(OPMEnexo.Usuario Usuario, int Id_Pedido)
        {
            return base.Channel.listarCadastroProdutoAsync(Usuario, Id_Pedido);
        }
        
        public System.Threading.Tasks.Task<OPMEnexo.wsRespostaListarPedido> listarCarrinhoAsync(OPMEnexo.Usuario Usuario, int Id_Pedido)
        {
            return base.Channel.listarCarrinhoAsync(Usuario, Id_Pedido);
        }
        
        public System.Threading.Tasks.Task<OPMEnexo.wsRespostaListarPedido> listarResgateFornecedorAsync(OPMEnexo.Usuario Usuario, int Id_Pedido)
        {
            return base.Channel.listarResgateFornecedorAsync(Usuario, Id_Pedido);
        }
        
        public System.Threading.Tasks.Task<OPMEnexo.wsRespostaListarPedido> listarRespostasPedidoAsync(OPMEnexo.Usuario Usuario, int Id_Pedido)
        {
            return base.Channel.listarRespostasPedidoAsync(Usuario, Id_Pedido);
        }
        
        public System.Threading.Tasks.Task<OPMEnexo.wsRespostaListarPedido> listarRespostasPedidoConfirmadoAsync(OPMEnexo.Usuario Usuario, int Id_Pedido)
        {
            return base.Channel.listarRespostasPedidoConfirmadoAsync(Usuario, Id_Pedido);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSPedidoPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSPedidoPort))
            {
                return new System.ServiceModel.EndpointAddress("https://www.opmenexo.com.br/opmenexo-wsEAR-opmenexo-ws/WSPedido");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WSPedidoClient.GetBindingForEndpoint(EndpointConfiguration.WSPedidoPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WSPedidoClient.GetEndpointAddress(EndpointConfiguration.WSPedidoPort);
        }
        
        public enum EndpointConfiguration
        {
            
            WSPedidoPort,
        }
    }
}
